### ISSUE TITLE
how should it be configured?

### ISSUE THREAD

**Issue by hbxgzhc** [deblockt/aria2-card#10]
I have two devices installed aria2, hass integration in the two devices normal access, now I want to add two cards, each card fixed display one of the devices aria2 running list, how should it be configured?

**Comment by deblockt** [comment]
Hi,

For the moment it is not possible. 
I have to make an evolution on the integration and the card to be able to do that.

**Comment by deblockt** [comment]
Hi, 

You can use the last version of the integration and of the card.
Now you can edit the card and select the aria server use.

If your entries has been created by old version of the integration all servers will be called "aria 2 configuration", you can rename it using the edit button of integration entry.
