### ISSUE TITLE
No downloads displayed

### ISSUE THREAD

**Issue by bearpawmaxim** [deblockt/aria2-card#8]
Steps to reproduce:
1. Open Lovelace in a panel (or refresh the browser window) that does not have an aria2-card
2. Go to the panel with aria2-card
3. Aria2-card does not show downloads

Technical details: connectedCallback is called, but hass property is empty.

**Comment by deblockt** [comment]
🤔 all work fine on my side. 
Which is your card version, and home assistant version?

**Comment by deblockt** [comment]
does this only happen with the latest version of the card?

**Comment by bearpawmaxim** [comment]
> does this only happen with the latest version of the card?

It happens with at least 3-4 last versions

**Comment by bearpawmaxim** [comment]
> Which is your card version, and home assistant version?

Everything is of latest versions

**Comment by deblockt** [comment]
it happens all the time, or it is random?

**Comment by bearpawmaxim** [comment]
Every time, when I open hass not on panel with aria2-card

**Comment by deblockt** [comment]
can you try with this branch https://github.com/deblockt/aria2-card/tree/fix/hassUndefinedIssue ?

**Comment by bearpawmaxim** [comment]
> can you try with this branch https://github.com/deblockt/aria2-card/tree/fix/hassUndefinedIssue ?

Thanks!
Not at home now, so can't build... In approx 5 hours will test

**Comment by bearpawmaxim** [comment]
> can you try with this branch

No, nothing's changed unfortunately...
When I switch to a panel with aria2-card, the `connectedCallback` is executed but it doesn't subscribes to event because of the `hass` property is not defined. After switching the panel to another and then back to those with aria2-card, the `connectedCallback` is executed and the `hass` property is defined so it subscribes to event, calls the service and updates the download list.

**Comment by bearpawmaxim** [comment]
@deblockt , moving subscribe code from `connectedCallback` to `firstUpdated` fixes my issue

**Comment by deblockt** [comment]
can you try with 0.0.13 version?

**Comment by bearpawmaxim** [comment]
> can you try with 0.0.13 version?

0.0.13 works like a charm :)
Thanks!
